### ISSUE TITLE
[Bug]: ES自动创建的索引类型不匹配

### ISSUE THREAD

**Issue by yuchengpei** [cubefs/compass#162]
### Contact Details

651276700@qq.com

### Is there an existing issue for this?

- [X] I have searched all the existing issues

### Priority

high

### Current Behavior

服务部署完成后，任务信息已经成功存储到ES集群中，但任务诊断无法获取数据，task-portal日志报错如下：
2023-11-24 10:20:10,077 ERROR 25138 [http-nio-7075-exec-10] [] : [c.o.c.p.service.impl.OneClickDiagnosisServiceImpl:286] can not find this applicationId from task-application, appId:application_1680836053707_132298
2023-11-24 10:20:10,087 ERROR 25138 [http-nio-7075-exec-10] [] : [com.oppo.cloud.portal.config.GlobalExceptionConfig:41] GlobalException:
java.lang.Exception: can not find this applicationId from yarn-app, appId:application_1680836053707_132298
        at com.oppo.cloud.portal.service.impl.OneClickDiagnosisServiceImpl.buildTaskApp(OneClickDiagnosisServiceImpl.java:295)
        at com.oppo.cloud.portal.service.impl.OneClickDiagnosisServiceImpl.submitTask(OneClickDiagnosisServiceImpl.java:225)
        at com.oppo.cloud.portal.service.impl.OneClickDiagnosisServiceImpl.diagnose(OneClickDiagnosisServiceImpl.java:104)
        at com.oppo.cloud.portal.controller.AppController.getAppDiagnose(AppController.java:136)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)

### Expected Behavior

期望可以正常读取到到ES中的任务数据

### Steps To Reproduce

```markdown
1、服务部署
2、服务版本为1.1.2
3、数据正常写入ES中
4、无法读取ES数据
5、发现使用日志的过滤条件curl -X POST "xxx.xxx.xxx.xxx:9200/compass-*/_search?pretty" -H 'Content-Type:application/json' -d '{"query":{"bool":{"filter":[{"term":{"id.keyword":{"value":"application_1680836053707_132343","boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}}}
无法获取数据
6、经排查是自动创建的索引类型与代码不匹配
```

**Comment by zebozhuang** [comment]
> ### Contact Details
> [651276700@qq.com](mailto:651276700@qq.com)
> 
> ### Is there an existing issue for this?
> * [x]  I have searched all the existing issues
> 
> ### Priority
> high
> 
> ### Current Behavior
> 服务部署完成后，任务信息已经成功存储到ES集群中，但任务诊断无法获取数据，task-portal日志报错如下： 2023-11-24 10:20:10,077 ERROR 25138 [http-nio-7075-exec-10] [] : [c.o.c.p.service.impl.OneClickDiagnosisServiceImpl:286] can not find this applicationId from task-application, appId:application_1680836053707_132298 2023-11-24 10:20:10,087 ERROR 25138 [http-nio-7075-exec-10] [] : [com.oppo.cloud.portal.config.GlobalExceptionConfig:41] GlobalException: java.lang.Exception: can not find this applicationId from yarn-app, appId:application_1680836053707_132298 at com.oppo.cloud.portal.service.impl.OneClickDiagnosisServiceImpl.buildTaskApp(OneClickDiagnosisServiceImpl.java:295) at com.oppo.cloud.portal.service.impl.OneClickDiagnosisServiceImpl.submitTask(OneClickDiagnosisServiceImpl.java:225) at com.oppo.cloud.portal.service.impl.OneClickDiagnosisServiceImpl.diagnose(OneClickDiagnosisServiceImpl.java:104) at com.oppo.cloud.portal.controller.AppController.getAppDiagnose(AppController.java:136) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
> 
> ### Expected Behavior
> 期望可以正常读取到到ES中的任务数据
> 
> ### Steps To Reproduce
> ```
> 1、服务部署
> 2、服务版本为1.1.2
> 3、数据正常写入ES中
> 4、无法读取ES数据
> 5、发现使用日志的过滤条件curl -X POST "xxx.xxx.xxx.xxx:9200/compass-*/_search?pretty" -H 'Content-Type:application/json' -d '{"query":{"bool":{"filter":[{"term":{"id.keyword":{"value":"application_1680836053707_132343","boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}}}
> 无法获取数据
> 6、经排查是自动创建的索引类型与代码不匹配
> ```
> 
> ### Compass Log
> _No response_
> 
> ### Anything else? (Additional Context)
> _No response_

Ok, thanks for your feedback, we will verify and fix it later or you can fix it and provide a pr.
