### ISSUE TITLE
[Question]: [task-parser] Unable to connect to datanode error while obtaining HDFS logs

### ISSUE THREAD

**Issue by fengjian1129** [cubefs/compass#215]
### What would you like to ask or discuss?

How to solve the following log error：
2024-04-07 15:25:39,511 INFO  30378 [task-thread-5] [] : [org.apache.hadoop.hdfs.DFSClient:1014] Could not obtain BP-381122457-10.90.120.42-1645669748740:blk_2547725467_1475400647 from any node:  No live nodes contain current block Block locations: DatanodeInfoWithStorage[10.xx.xxx.xx:10040,DS-d1d6d359-3b9a-46a8-83d4-cae4d17c94fb,DISK] DatanodeInfoWithStorage[10.xx.xxx.xx:10040,DS-7b9f2b30-498a-4e14-abab-f321b61be13a,DISK] DatanodeInfoWithStorage[10.xx.xxx.xx:10040,DS-8d253c0e-193a-4754-939d-923b7940c342,DISK] Dead nodes:  DatanodeInfoWithStorage[10.xx.xxx.xx:10040,DS-7b9f2b30-498a-4e14-abab-f321b61be13a,DISK] DatanodeInfoWithStorage[10.xx.xxx.xx:10040,DS-d1d6d359-3b9a-46a8-83d4-cae4d17c94fb,DISK] DatanodeInfoWithStorage[10.xx.xxx.xx:10040,DS-8d253c0e-193a-4754-939d-923b7940c342,DISK]. Will get new block locations from namenode and retry... 

2024-04-07 15:25:56,682 ERROR 30378 [task-thread-5] [] : [c.o.c.parser.service.job.parser.CommonTextParser:108] Exception: 
org.apache.hadoop.hdfs.BlockMissingException: Could not obtain block: BP-381122457-10.xx.xxx.xx-1645669748740:blk_2547725467_1475400647 file=/tmp/logs/jd-dw/logs/application_1710319269926_593099/xxx-xxxxxx.baidu.internal_8041 No live nodes contain current block Block locations: DatanodeInfoWithStorage[10.xx.xxx.xx:10040,DS-8d253c0e-193a-4754-939d-923b7940c342,DISK] DatanodeInfoWithStorage[10.xx.xxx.xx:10040,DS-7b9f2b30-498a-4e14-abab-f321b61be13a,DISK] DatanodeInfoWithStorage[10.xx.xxx.xx:10040,DS-d1d6d359-3b9a-46a8-83d4-cae4d17c94fb,DISK] Dead nodes:  DatanodeInfoWithStorage[10.xx.xxx.xx:10040,DS-7b9f2b30-498a-4e14-abab-f321b61be13a,DISK] DatanodeInfoWithStorage[10.xx.xxx.xx:10040,DS-d1d6d359-3b9a-46a8-83d4-cae4d17c94fb,DISK] DatanodeInfoWithStorage[10.xx.xxx.xx:10040,DS-8d253c0e-193a-4754-939d-923b7940c342,DISK]
	at org.apache.hadoop.hdfs.DFSInputStream.refetchLocations(DFSInputStream.java:1007)
	at org.apache.hadoop.hdfs.DFSInputStream.chooseDataNode(DFSInputStream.java:990)
	at org.apache.hadoop.hdfs.DFSInputStream.chooseDataNode(DFSInputStream.java:969)
	at org.apache.hadoop.hdfs.DFSInputStream.blockSeekTo(DFSInputStream.java:677)
	at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:884)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:957)

**Comment by nilnon** [comment]
@fengjian1129 You can check the health status of the datanode, if there is no problem, task-parser needs to add some retries.

**Comment by fengjian1129** [comment]
> task-parser needs to add some retries.

thx
