### ISSUE TITLE
[Bug]: The log reading option is single, does not support the YARN log directory structure of Hadoop 3.3.0 version, and does not support reading log files with suffix compression formats.

### ISSUE THREAD

**Issue by slight-leaves** [cubefs/compass#36]
### 报错信息
2023-05-09 08:01:10,890 ERROR 53279 [task-thread-5] [] : [c.o.c.p.service.job.parser.SparkExecutorLogParser:80] Exception:
java.io.FileNotFoundException: File hdfs://cluster1/tmp/logs/hadoop/logs/application_1682060914400_0287 does not exist.
        at org.apache.hadoop.hdfs.DistributedFileSystem$DirListingIterator.<init>(DistributedFileSystem.java:1282)
        at org.apache.hadoop.hdfs.DistributedFileSystem$DirListingIterator.<init>(DistributedFileSystem.java:1256)
        at org.apache.hadoop.hdfs.DistributedFileSystem$25.doCall(DistributedFileSystem.java:1201)
        at org.apache.hadoop.hdfs.DistributedFileSystem$25.doCall(DistributedFileSystem.java:1197)
        at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
        at org.apache.hadoop.hdfs.DistributedFileSystem.listLocatedStatus(DistributedFileSystem.java:1215)
        at org.apache.hadoop.fs.FileSystem.listLocatedStatus(FileSystem.java:2162)
        at org.apache.hadoop.fs.FileSystem$5.<init>(FileSystem.java:2288)
        at org.apache.hadoop.fs.FileSystem.listFiles(FileSystem.java:2285)
        at com.oppo.cloud.parser.utils.HDFSUtil.listFiles(HDFSUtil.java:149)
        at com.oppo.cloud.parser.service.reader.HDFSReader.listFiles(HDFSReader.java:56)
        at com.oppo.cloud.parser.service.reader.HDFSReader.getReaderObjects(HDFSReader.java:72)
        at com.oppo.cloud.parser.service.job.parser.SparkExecutorLogParser.run(SparkExecutorLogParser.java:78)
        at com.oppo.cloud.parser.service.job.task.Task.lambda$createFutures$0(Task.java:67)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
### 原因
https://issues.apache.org/jira/browse/YARN-6929
新版本的日志路径结构{aggregation_log_root}/{user}/bucket_{suffix}/{bucket1}/{appId}
### 建议支持多种压缩格式日志的读取
可以添加到配置里供用户选择读取的压缩格式，亦或者读取相关配置文件。
如：spark历史服务配置中相关的日志压缩配置项
### 其它建议
可以适当性的出一些主流版本调度器的task-syncer映射关系配置项。
减少普通用户的搭建成本

**Comment by nilnon** [comment]
@slight-leaves Thanks for your feedback, we will support hadoop 3.3.0 version log directory structure and spark compression configuration.

**Comment by zebozhuang** [comment]
@slight-leaves We have fixed it. If you meet any question about compass, please launch issue and we will try to solve it.
